version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      internval: "weekly"

  - package-ecosystem: "poetry"
    directory: "/"
    schedule:
      internval: "weekly"
    
  - package-ecosystem: "npm"
    directory: "/bootstrap"
    schedule:
      interval: "weekly"
