services:
    mysql:
        image: mysql
        restart: unless-stopped
        ports:
            - '13306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: pandora
            MYSQL_USER: pandora
            MYSQL_PASSWORD: pandora
            MYSQL_DATABASE: pandora
    redis:
        image: redis
        restart: unless-stopped
        ports:
            - '16379:6379'
