# Generated by Django 4.0.4 on 2022-04-19 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editions', '0003_change_team_unique'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='edition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='editions.edition'),
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('edition', 'name')},
        ),
    ]
