# Generated by Django 4.1.5 on 2023-01-05 16:00

import pandora.teams.models.team
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_change_team_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='join_code',
            field=models.CharField(default=pandora.teams.models.team._generate_join_code, max_length=32),
        ),
    ]
