# Generated by Django 4.1.5 on 2023-01-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_add_team_join_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('BACKUP', 'Backup')], default='ACTIVE', max_length=16),
            preserve_default=False,
        ),
    ]
