# Generated by Django 4.1.5 on 2023-01-06 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_add_team_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('BACKUP', 'Backup')], default='ACTIVE', max_length=16),
        ),
    ]
