# Generated by Django 4.1.5 on 2023-01-07 12:44

import pandora.teams.models.team
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_fix_team_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=pandora.teams.models.team._get_team_upload_path),
        ),
    ]
