# Generated by Django 4.1.5 on 2023-01-08 17:18

import pandora.teams.models.team_member
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_fix_team_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='code',
            field=models.CharField(default=pandora.teams.models.team_member._generate_team_member_code, max_length=64),
        ),
    ]
