# Generated by Django 4.1.5 on 2023-01-08 17:20

import pandora.teams.models.team_member
from django.db import migrations, models


def generate_team_member_codes(django_apps, _schema_editor):
    TeamMember = django_apps.get_model('teams', 'TeamMember')
    for team_member in TeamMember.objects.all():
        team_member.code = pandora.teams.models.team_member._generate_team_member_code()
        team_member.save(update_fields=['code'])


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_add_team_member_code'),
    ]

    operations = [
        migrations.RunPython(code=generate_team_member_codes, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='teammember',
            name='code',
            field=models.CharField(default=pandora.teams.models.team_member._generate_team_member_code, max_length=64, unique=True),
        ),
    ]
