# Generated by Django 4.0.3 on 2022-03-31 22:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('editions', '0002_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puzzles', to='editions.edition')),
            ],
        ),
        migrations.CreateModel(
            name='PuzzleCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('number', models.PositiveSmallIntegerField()),
                ('code', models.CharField(max_length=32)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puzzle_codes', to='editions.day')),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='puzzles.puzzle')),
            ],
        ),
        migrations.CreateModel(
            name='Solve',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solves', to='puzzles.puzzlecode')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solves', to='teams.teammember')),
            ],
        ),
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('IN_PROGRESS', 'In Progress'), ('FINISHED', 'Finished'), ('CANCELED', 'Canceled')], default='WAITING', max_length=32)),
                ('comment', models.TextField()),
                ('phone_number', models.CharField(blank=True, max_length=32, null=True)),
                ('committee_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hints', to='editions.committeemember')),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hints', to='puzzles.puzzle')),
                ('score_modification', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hint', to='editions.scoremodification')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hints', to='teams.team')),
            ],
        ),
    ]
