# Generated by Django 4.1.5 on 2023-01-06 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_add_team_status'),
        ('puzzles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solve',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solves', to='teams.team'),
        ),
    ]
