# Generated by Django 4.1.5 on 2023-01-07 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_fix_team_image'),
        ('editions', '0007_fix_unique_together'),
        ('puzzles', '0003_add_default_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hint',
            unique_together={('puzzle', 'team')},
        ),
        migrations.AlterUniqueTogether(
            name='puzzlecode',
            unique_together={('day', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='solve',
            unique_together={('code', 'team')},
        ),
    ]
