# Generated by Django 4.1.7 on 2023-04-19 19:37

from django.db import migrations, models
import django.db.models.deletion
import pandora.puzzles.models.puzzle_file
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('editions', '0018_fix_score_modification'),
        ('puzzles', '0004_fix_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzlecode',
            name='day',
            field=models.ForeignKey(blank=True, help_text='Leaving the day blank makes it a bonus puzzle.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='puzzle_codes', to='editions.day'),
        ),
        migrations.CreateModel(
            name='PuzzleFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('PUZZLE', 'Puzzle'), ('OTHER', 'Other')], max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=pandora.puzzles.models.puzzle_file._get_puzzle_file_upload_path)),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='puzzles.puzzle')),
            ],
            options={
                'unique_together': {('puzzle', 'name')},
            },
        ),
    ]
