# Generated by Django 4.1.7 on 2023-04-29 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_change_team_member_code'),
        ('puzzles', '0005_add_puzzle_file'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hint',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='hint',
            name='code',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='hints', to='puzzles.puzzlecode'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='hint',
            unique_together={('code', 'team')},
        ),
        migrations.RemoveField(
            model_name='hint',
            name='puzzle',
        ),
    ]
