# Generated by Django 4.1.7 on 2023-04-29 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0006_change_hint_puzzle_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hint',
            name='score_modification',
        ),
    ]
