# Generated by Django 4.1.7 on 2023-04-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0007_remove_hint_score_modification'),
    ]

    operations = [
        migrations.AddField(
            model_name='hint',
            name='committee_comment',
            field=models.TextField(blank=True),
        ),
    ]
