# Generated by Django 4.1.7 on 2023-04-29 17:36

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0008_add_hint_committee_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='location_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='location_point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='solution',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='solution_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='solution_direction',
            field=models.CharField(choices=[('NONE', 'None'), ('NORTH_WEST', 'North-West'), ('NORTH', 'North'), ('NORTH_EAST', 'North-East'), ('EAST', 'East'), ('SOUTH_EAST', 'South-East'), ('SOUTH', 'South'), ('SOUTH_WEST', 'South-West'), ('WEST', 'West')], default='NONE', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='puzzle',
            name='solution_distance',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Distance in meters between the solution and the puzzle code. Should be left blank most of the time.', null=True),
        ),
        migrations.AlterField(
            model_name='puzzlefile',
            name='type',
            field=models.CharField(choices=[('PUZZLE', 'Puzzle'), ('SOLUTION', 'Solution'), ('OTHER', 'Other')], max_length=32),
        ),
    ]
