# Generated by Django 4.1.7 on 2023-04-30 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0009_add_puzzle_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzlecode',
            name='puzzle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='code', to='puzzles.puzzle'),
        ),
    ]
