# Generated by Django 4.0.3 on 2022-03-31 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        ('editions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scoremodification',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_modifications', to='teams.team'),
        ),
        migrations.AddField(
            model_name='scoremodification',
            name='team_member',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='score_modifications', to='teams.teammember'),
        ),
        migrations.AddField(
            model_name='killcode',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kill_codes', to='editions.day'),
        ),
        migrations.AddField(
            model_name='killcode',
            name='team_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kill_codes', to='teams.teammember'),
        ),
        migrations.AddField(
            model_name='kill',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kills', to='editions.killcode'),
        ),
        migrations.AddField(
            model_name='kill',
            name='killer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kills', to='teams.teammember'),
        ),
        migrations.AddField(
            model_name='day',
            name='edition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='editions.edition'),
        ),
        migrations.AddField(
            model_name='committeemember',
            name='edition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_members', to='editions.edition'),
        ),
        migrations.AddField(
            model_name='committeemember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='absence',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='editions.day'),
        ),
        migrations.AddField(
            model_name='absence',
            name='team_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='teams.teammember'),
        ),
    ]
