# Generated by Django 4.0.4 on 2022-04-19 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editions', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='edition',
            options={'get_latest_by': 'year'},
        ),
    ]
