# Generated by Django 4.1.5 on 2023-01-06 18:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('editions', '0004_change_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditionSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=255)),
                ('value', models.TextField(blank=True, null=True)),
                ('edition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='editions.edition')),
            ],
            options={
                'unique_together': {('edition', 'key')},
            },
        ),
    ]
