# Generated by Django 4.1.5 on 2023-01-07 12:44

import pandora.editions.models.kill_code
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editions', '0005_add_edition_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='killcode',
            name='code',
            field=models.CharField(default=pandora.editions.models.kill_code._generate_kill_code, max_length=32),
        ),
    ]
