# Generated by Django 4.1.5 on 2023-01-07 13:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_fix_team_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('editions', '0006_add_default_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='absence',
            unique_together={('day', 'team_member')},
        ),
        migrations.AlterUniqueTogether(
            name='committeemember',
            unique_together={('edition', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='killcode',
            unique_together={('day', 'code'), ('day', 'team_member')},
        ),
    ]
