# Generated by Django 4.1.5 on 2023-01-07 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editions', '0007_fix_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kill',
            name='code',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kill', to='editions.killcode'),
        ),
    ]
