# Generated by Django 4.1.5 on 2023-01-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editions', '0008_fix_kill_code_kill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoremodification',
            name='type',
            field=models.CharField(choices=[('BONUS', 'Bonus'), ('OFFENCE', 'Offence')], max_length=32),
        ),
    ]
