# Generated by Django 4.1.5 on 2023-01-08 18:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_change_team_member_code'),
        ('editions', '0009_fix_score_modification_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='editions.edition')),
            ],
            options={
                'unique_together': {('edition', 'name')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='absence',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='absence',
            name='event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='editions.event'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='absence',
            unique_together={('event', 'team_member')},
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='editions.event')),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='teams.teammember')),
            ],
            options={
                'unique_together': {('event', 'team_member')},
            },
        ),
        migrations.RemoveField(
            model_name='absence',
            name='day',
        ),
    ]
