# Generated by Django 4.1.5 on 2023-01-18 11:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('editions', '0010_add_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditionMediaItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True)),
                ('file', models.FileField(blank=True, upload_to='')),
                ('is_hidden', models.BooleanField(default=True)),
                ('sort_index', models.PositiveSmallIntegerField()),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='editions.edition')),
            ],
        ),
    ]
