# Generated by Django 4.1.5 on 2023-01-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editions', '0011_add_edition_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='editionmediaitem',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
