# Generated by Django 4.1.5 on 2023-01-18 12:38

import pandora.editions.models.edition_media_item
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editions', '0012_change_edition_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editionmediaitem',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=pandora.editions.models.edition_media_item._get_edition_media_item_upload_path),
        ),
    ]
