# Generated by Django 4.1.5 on 2023-01-18 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_change_team_member_code'),
        ('editions', '0013_fix_edition_media'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Absence',
            new_name='EventAbsence',
        ),
        migrations.RenameModel(
            old_name='Presence',
            new_name='EventPresence',
        ),
    ]
