# Generated by Django 4.1.7 on 2023-04-02 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editions', '0016_add_edition_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='committeemember',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
