# Generated by Django 4.1.7 on 2023-04-19 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editions', '0018_fix_score_modification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoremodification',
            name='amount',
            field=models.SmallIntegerField(help_text='Amounts are absolute, so bonus is positive, offence is negative.'),
        ),
    ]
