# Generated by Django 4.2.1 on 2023-05-12 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editions', '0020_add_base_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='editionmediaitem',
            name='type',
            field=models.CharField(choices=[('AUDIO', 'Audio'), ('VIDEO', 'Video'), ('OTHER', 'Other')], default='VIDEO', max_length=32),
            preserve_default=False,
        ),
    ]
