# Generated by Django 4.2.1 on 2024-01-29 17:43

from django.db import migrations, models
import django.db.models.deletion
import pandora.core.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0010_add_base_model'),
        ('editions', '0021_add_edition_media_item_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveScore',
            fields=[
                ('id', pandora.core.fields.UUID4Field(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('type', models.CharField(choices=[('DAY', 'Day'), ('BONUS', 'Bonus'), ('OTHER', 'Other'), ('TOTAL', 'Total')], max_length=32)),
                ('score', models.PositiveSmallIntegerField()),
                ('day', models.ForeignKey(blank=True, help_text='Leaving the day blank makes it a bonus puzzle.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archive_scores', to='editions.day')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archive_scores', to='teams.team')),
            ],
            options={
                'unique_together': {('type', 'day', 'team')},
            },
        ),
    ]
