# Generated by Django 5.0.1 on 2024-02-04 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editions', '0022_add_archive_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivescore',
            name='score',
            field=models.SmallIntegerField(help_text='Amounts are absolute, so bonus is positive, offence is negative.'),
        ),
        migrations.AlterField(
            model_name='archivescore',
            name='type',
            field=models.CharField(choices=[('DAY', 'Day'), ('BONUS', 'Bonus'), ('OFFENCE', 'Offence'), ('OTHER', 'Other'), ('TOTAL', 'Total')], max_length=32),
        ),
    ]
