# Generated by Django 5.0.2 on 2024-02-13 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editions', '0024_change_committee_member'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='committeemember',
            unique_together=set(),
        ),
    ]
