# Generated by Django 4.1.7 on 2023-04-02 10:42

from django.db import migrations, models
import django.db.models.deletion
import pandora.pregames.models.pregame_puzzle_code
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('editions', '0017_add_committee_member_is_hidden'),
        ('teams', '0008_change_team_member_code'),
        ('puzzles', '0004_fix_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregame',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('edition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pregame', to='editions.edition')),
            ],
        ),
        migrations.CreateModel(
            name='PregamePuzzleCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('number', models.PositiveSmallIntegerField()),
                ('code', models.CharField(default=pandora.pregames.models.pregame_puzzle_code._generate_pregame_puzzle_code, max_length=32)),
                ('pregame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puzzle_codes', to='pregames.pregame')),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pregame_codes', to='puzzles.puzzle')),
            ],
            options={
                'unique_together': {('pregame', 'code')},
            },
        ),
        migrations.CreateModel(
            name='PregameSolve',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solves', to='pregames.pregamepuzzlecode')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pregame_solves', to='teams.team')),
            ],
            options={
                'unique_together': {('code', 'team')},
            },
        ),
    ]
