# Generated by Django 4.1.7 on 2023-04-30 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0010_change_puzzle_code_puzzle'),
        ('pregames', '0002_add_pregame_bonus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregamepuzzlecode',
            name='puzzle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pregame_code', to='puzzles.puzzle'),
        ),
    ]
