# Generated by Django 4.2.1 on 2023-05-12 12:50

from django.db import migrations, models
import django.utils.timezone
import pandora.core.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pregames', '0003_change_pregame_puzzle_code_puzzle'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregame',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pregame',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AddField(
            model_name='pregamepuzzlecode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AddField(
            model_name='pregamesolve',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='pregame',
            name='id',
            field=pandora.core.fields.UUID4Field(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pregamepuzzlecode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='pregamepuzzlecode',
            name='id',
            field=pandora.core.fields.UUID4Field(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pregamesolve',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='pregamesolve',
            name='id',
            field=pandora.core.fields.UUID4Field(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
